Repository ConSeat/backend, pull requests merged in 2025-04, with the labels that each got.

#37 test : 이미지 업로드 테스트 작성
  concertseat/src/main/java/site/concertseat/domain/review/controller/ReviewController.java
  concertseat/src/main/java/site/concertseat/global/jwt/service/JwtUtils.java
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
Labels: ✅ test

#40 test : 콘서트장 목록 조회 성공 테스트 작성
  concertseat/src/test/java/site/concertseat/domain/stadium/controller/StadiumControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✅ test

#39 feat : 콘서트장 Section 및 Seating 리스트 조회 구현
  concertseat/src/main/java/site/concertseat/domain/stadium/controller/StadiumController.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/FloorSectionDto.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/SeatingListRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/SeatingWithCountDto.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/SectionIdDto.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/SectionListRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/repository/StadiumRepository.java
  concertseat/src/main/java/site/concertseat/domain/stadium/service/StadiumService.java
  concertseat/src/main/java/site/concertseat/domain/stadium/service/StadiumServiceImpl.java
Labels: ✨ feat

#41 feat : 구글 로그인 추가
  concertseat/src/main/java/site/concertseat/global/oauth/CustomOAuth2UserService.java
  concertseat/src/main/java/site/concertseat/global/oauth/response/GoogleResponse.java
  concertseat/src/main/resources/application.yml
Labels: ✨ feat

#43 feat : 콘서트장 목록 조회 시 전체 리뷰 개수 조회되도록 변경
  concertseat/build.gradle
  concertseat/src/main/java/site/concertseat/domain/review/repository/ReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewService.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/StadiumListRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/service/StadiumServiceImpl.java
  concertseat/src/main/java/site/concertseat/global/config/CachingConfig.java
  concertseat/src/test/java/site/concertseat/domain/stadium/controller/StadiumControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✨ feat, ✅ test

#46 feat : 내 정보 조회 기능 구현
  concertseat/src/main/java/site/concertseat/domain/bookmark/repository/BookmarkRepository.java
  concertseat/src/main/java/site/concertseat/domain/member/controller/MemberController.java
  concertseat/src/main/java/site/concertseat/domain/member/dto/MemberInfo.java
  concertseat/src/main/java/site/concertseat/domain/member/dto/res/MemberSearchRes.java
  concertseat/src/main/java/site/concertseat/domain/member/repository/MemberRepository.java
  concertseat/src/main/java/site/concertseat/domain/member/service/MemberService.java
  concertseat/src/main/java/site/concertseat/domain/member/service/MemberServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ReviewRepository.java
  concertseat/src/test/java/site/concertseat/domain/member/controller/MemberControllerTest.java
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✨ feat, ✅ test

#50 feat : 리뷰 상세조회 기능 구현
  concertseat/src/main/java/site/concertseat/domain/bookmark/repository/BookmarkRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/controller/ReviewController.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/ReviewListReq.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/ReviewListRes.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/CustomReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/CustomReviewRepositoryImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/FeatureRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/LikesRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ObstructionRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/SightRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewService.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewServiceImpl.java
  concertseat/src/main/java/site/concertseat/global/dto/SliceDto.java
Labels: ✨ feat

#53 feat : 나의 후기 목록 기능 구현
  concertseat/src/main/java/site/concertseat/domain/review/controller/ReviewController.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/MyReviewDto.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/MyReviewStadiumDto.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/req/MyReviewSearchReq.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/req/ReviewListReq.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/req/ReviewPostReq.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/ImageUploadRes.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/MyReviewSearchRes.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/MyReviewStadiumListRes.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/ReviewListRes.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/ReviewSearchRes.java
  concertseat/src/main/java/site/concertseat/domain/review/entity/Review.java
  concertseat/src/main/java/site/concertseat/domain/review/enums/ReviewStatus.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/CustomReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/CustomReviewRepositoryImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewService.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewServiceImpl.java
  concertseat/src/test/java/site/concertseat/domain/bookmark/controller/BookmarkControllerTest.java
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✨ feat, 🚚 rename, ✅ test

#55 feat : 북마크한 좌석 시야 상세 정보 조회 기능 구현
  concertseat/src/main/java/site/concertseat/domain/bookmark/controller/BookmarkController.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/dto/ReviewDetailDto.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/dto/res/BookmarkReviewDetailRes.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/repository/BookmarkRepository.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/service/BookmarkService.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/service/BookmarkServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/FeatureRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ObstructionRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/SightRepository.java
  concertseat/src/test/java/site/concertseat/domain/bookmark/controller/BookmarkControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✨ feat, ✅ test

#58 feat : 북마크 추가 / 해제 기능 구현
  concertseat/src/main/java/site/concertseat/domain/bookmark/entity/Bookmark.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/repository/BookmarkRepository.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/service/BookmarkService.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/service/BookmarkServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/controller/ReviewController.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ReviewRepository.java
  concertseat/src/main/java/site/concertseat/global/entity/BaseEntity.java
Labels: ✨ feat

#59 feat : 내 후기 상세보기 기능 구현
  concertseat/src/main/java/site/concertseat/domain/bookmark/repository/BookmarkRepository.java
  concertseat/src/main/java/site/concertseat/domain/bookmark/service/BookmarkServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/controller/ReviewController.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/MyReviewDetailDto.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/MyReviewDetailRes.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewService.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewServiceImpl.java
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✨ feat, ✅ test

#62 feat : 어드민 리뷰 승인 기능 구현
  concertseat/src/main/java/site/concertseat/domain/admin/controller/AdminController.java
  concertseat/src/main/java/site/concertseat/domain/admin/dto/req/ApproveReviewReq.java
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminService.java
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/member/enums/Role.java
  concertseat/src/main/java/site/concertseat/domain/review/entity/Review.java
  concertseat/src/main/java/site/concertseat/domain/review/repository/ReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewService.java
  concertseat/src/main/java/site/concertseat/domain/review/service/ReviewServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/StadiumListRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/service/StadiumServiceImpl.java
  concertseat/src/main/java/site/concertseat/global/aop/AdminLogAspect.java
  concertseat/src/main/java/site/concertseat/global/config/SecurityConfig.java
  concertseat/src/main/java/site/concertseat/global/oauth/response/OAuth2Response.java
  concertseat/src/main/resources/logback-spring.xml
Labels: ✨ feat

#65 feat : CORS 설정 추가
  concertseat/src/main/java/site/concertseat/domain/review/dto/res/ReviewSearchRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/FloorDto.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/SectionListRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/StadiumDetailsRes.java
  concertseat/src/main/java/site/concertseat/domain/stadium/dto/StadiumListRes.java
  concertseat/src/main/java/site/concertseat/global/config/SecurityConfig.java
Labels: ✨ feat

#67 feat : 프로필 정보 조회 기능 구현
  concertseat/src/main/java/site/concertseat/domain/member/controller/MemberController.java
  concertseat/src/main/java/site/concertseat/domain/member/dto/res/MemberProfileRes.java
  concertseat/src/main/java/site/concertseat/domain/member/repository/MemberRepository.java
  concertseat/src/main/java/site/concertseat/domain/member/service/MemberService.java
  concertseat/src/main/java/site/concertseat/domain/member/service/MemberServiceImpl.java
  concertseat/src/main/resources/application-deploy.yml
  concertseat/src/test/java/site/concertseat/domain/member/controller/MemberControllerTest.java
Labels: ✨ feat, ✅ test

#69 feat : section에서 src 속성 삭제
  concertseat/src/main/java/site/concertseat/domain/stadium/entity/Section.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✨ feat

#71 fix : cors 설정 수정
  concertseat/src/main/java/site/concertseat/global/config/SecurityConfig.java
Labels: 🐛 fix

#73 test : 좋아요 추가 및 해제 테스트 코드 작성
  concertseat/src/main/java/site/concertseat/domain/review/controller/ReviewController.java
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✅ test

#75 test : 북마크 추가 및 해제 테스트 코드 작성
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
  concertseat/src/test/resources/sql/data.sql
Labels: ✅ test

#80 feat : 어드민 리뷰 조회 기능 구현
  concertseat/src/main/java/site/concertseat/domain/admin/controller/AdminController.java
  concertseat/src/main/java/site/concertseat/domain/admin/dto/AdminReviewDto.java
  concertseat/src/main/java/site/concertseat/domain/admin/dto/BookmarksAndLikesCountDto.java
  concertseat/src/main/java/site/concertseat/domain/admin/dto/req/AdminReviewListReq.java
  concertseat/src/main/java/site/concertseat/domain/admin/dto/res/AdminReviewListRes.java
  concertseat/src/main/java/site/concertseat/domain/admin/repository/AdminReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/admin/repository/CustomAdminReviewRepository.java
  concertseat/src/main/java/site/concertseat/domain/admin/repository/CustomAdminReviewRepositoryImpl.java
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminService.java
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/dto/req/ReviewPostReq.java
  concertseat/src/main/java/site/concertseat/global/dto/PageDto.java
  concertseat/src/main/java/site/concertseat/global/util/DateFormatter.java
Labels: ✨ feat

#82 test : 구역 후기 보기 테스트 작성
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
  concertseat/src/test/resources/application.yml
  concertseat/src/test/resources/sql/data.sql
Labels: ✅ test

#84 feat : 리뷰 정렬 기준 변경
  concertseat/src/main/java/site/concertseat/domain/review/repository/CustomReviewRepositoryImpl.java
  concertseat/src/test/java/site/concertseat/domain/review/controller/ReviewControllerTest.java
Labels: ✨ feat

#89 feat : 리뷰 상태 approved로 변경 시 이미지 압축
  concertseat/src/main/java/site/concertseat/domain/admin/controller/AdminController.java
  concertseat/src/main/java/site/concertseat/domain/admin/dto/req/ChangeReviewStatusReq.java
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminService.java
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminServiceImpl.java
  concertseat/src/main/java/site/concertseat/domain/review/entity/Sight.java
  concertseat/src/main/java/site/concertseat/global/aop/AdminLogAspect.java
  concertseat/src/main/java/site/concertseat/global/s3/S3Service.java
  concertseat/src/main/java/site/concertseat/global/s3/S3ServiceImpl.java
Labels: ✨ feat

#91 fix : 이미지 압축시 회전하는 문제 수정
  concertseat/build.gradle
  concertseat/src/main/java/site/concertseat/domain/admin/service/AdminServiceImpl.java
  concertseat/src/main/java/site/concertseat/global/s3/S3Service.java
  concertseat/src/main/java/site/concertseat/global/s3/S3ServiceImpl.java
Labels: 🐛 fix

#93 feat : 어드민 유저 로그인 후 콜백 주소 변경
  concertseat/src/main/java/site/concertseat/global/oauth/Oauth2SuccessHandler.java
Labels: ✨ feat

#99 feat : 로그인 response 변경
  concertseat/src/main/java/site/concertseat/global/config/SecurityConfig.java
  concertseat/src/main/java/site/concertseat/global/jwt/service/JwtUtils.java
  concertseat/src/main/java/site/concertseat/global/security/CustomAuthenticationEntryPoint.java
  concertseat/src/main/java/site/concertseat/global/statuscode/ErrorCode.java
Labels: ✨ feat

#101 fix : Member 정보 수정 반영 안되는 문제 해결
  concertseat/src/main/java/site/concertseat/domain/member/service/MemberServiceImpl.java
Labels: 🐛 fix

#103 fix : review 개수 오류 수정
  concertseat/src/main/java/site/concertseat/domain/review/repository/CustomReviewRepositoryImpl.java
Labels: 🐛 fix
